# Project information 
site_name: 六楼溜刘的小窝
site_description: 这是一个中学 OIer 的博客，他会在这里分享一些算法和题解，喜欢可以进来贴贴。
site_author: 六楼溜刘 aka six-floor-slip-liu
site_url: https://x-six-floor-slip-liu-x.github.io/

# Repository 
repo_name: X-six-floor-slip-liu-X/六楼溜刘的小窝
repo_url: https://github.com/X-six-floor-slip-liu-X/X-six-floor-slip-liu-X.github.io

# Copyright 
copyright: Built by <a href="http://robinyqc.cn"> robinyqc.</a> 

# Configuration
theme:
  name: material # 不能改
  language: zh # 中文   
  language: en # English 
  custom_dir: custom # 不能改
  favicon: assets/favicon.png   
  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: teal
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: cyan
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: fontawesome/solid/earth-americas
    repo: fontawesome/brands/github

  features:
    - navigation.tabs # 这一项将 nav 的顶级标题置顶
    - navigation.top # 返回顶部标签

# Customization
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/robinyqc

extra_javascript:
  - js/mathjax/tex-chtml.js # 不能改


# Extensions 不能改
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tilde
  - toc:
      permalink: false

# 目录（导航）
# 格式： - 名称: 路径（通常是相对路径）
# 使用缩进来表示子目录。
nav:
  - Preface: index.md
  - I 杂项:
    - 1 新博客建立啦: misc/new.md
    - 2 MarkDown 常用语法: misc/try_md.md